name: Test Data Pipeline for Silver

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: run pipeline code
        run: python test_postgres.py

      - name: Run tests
        run: pytest .